name: yolo
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - albucore=0.0.24=pyhd8ed1ab_0
  - albumentations=2.0.8=pyhd8ed1ab_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - aom=3.6.0=h6a678d5_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py311haa0f9ac_1
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotlicffi=1.2.0.0=py311h7354ed3_0
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h44eff21_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py311h4eded50_1
  - charset-normalizer=3.4.4=py311h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311hdf67eae_3
  - cpython=3.11.14=py311hd8ed1ab_2
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h5bd4931_0
  - debugpy=1.8.18=py311hc665b79_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=h5888daf_0
  - eigen=3.4.0=h171cf75_1
  - eval-type-backport=0.3.1=pyhd8ed1ab_0
  - eval_type_backport=0.3.1=pyha770c72_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h3385a95_0
  - ffmpeg=6.1.1=h2a67f75_3
  - filelock=3.20.0=py311h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h2c49b7f_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py311h3778330_0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.10=h7b6447c_0
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.5.0=h48cff8f_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.2=py311ha78e65c_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=hecca717_2
  - gst-plugins-base=1.24.12=hc146dc4_1
  - gstreamer=1.24.12=hb6d4d65_1
  - gstreamer-orc=0.4.41=h17648ed_0
  - h5py=3.15.1=py311hea18c50_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - hdf5=1.14.5=h2b7332f_2
  - icu=73.1=h6a678d5_0
  - imageio=2.37.2=py311h7040dfc_0
  - impi_rt=2021.13.1=ha770c72_769
  - intel-openmp=2023.0.0=h9e868ea_25371
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.8.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py311h06a4308_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jpeg=9f=h5ce9db8_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py311h724c32c_2
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.8.2=h3ec8f01_0
  - libavif=1.1.1=h5eee18b_0
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libclang13=14.0.6=default_he11475f_2
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.5.147=0
  - libcurl=8.17.0=h4e3cde8_1
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h37c7471_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_16
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm14=14.0.6=hecde1de_4
  - libllvm15=15.0.7=he89c38a_4
  - libnghttp2=1.67.0=had1ee68_0
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvjpeg=11.9.0.86=0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=h46f56fc_2
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.53=h421ea60_0
  - libpq=17.6=ha51bf15_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.1=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libtasn1=4.20.0=ha30cf84_0
  - libtheora=1.1.1=h4ab18f5_1006
  - libtiff=4.7.1=h029b1ac_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h54a6638_2
  - libvpx=1.13.1=h59595ed_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp=1.6.0=h089d785_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.9.1=h69220b7_0
  - libxkbfile=1.1.0=hf54ef8a_2
  - libxml2=2.13.9=h2c43086_0
  - libxslt=1.1.43=h28b3bda_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=14.0.6=h9e868ea_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py311h5eee18b_0
  - matplotlib=3.10.8=py311h38be061_0
  - matplotlib-base=3.10.8=py311h0f3be63_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mesalib=25.1.5=h31e3550_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-include=2023.1.0=h06a4308_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpi=1.0=impi
  - mpi4py=4.1.1=py311h1496390_102
  - mpmath=1.3.0=py311h06a4308_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql=8.4.0=h721767e_2
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.6.1=py311h06a4308_0
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - numexpr=2.11.0=py311hf4471f9_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - opencv=4.10.0=py311h6030d24_7
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h23c847b_1
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - polars=1.36.1=pyh6a1acc5_0
  - polars-runtime-32=1.36.1=py310hffdcd12_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py311haee01d2_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pycparser=2.23=py311h06a4308_0
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py311h902ca64_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyside6=6.7.3=py311hfe4ef28_1
  - pysocks=1.7.1=py311h06a4308_1
  - python=3.11.9=h955ad1f_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.11.14=hd8ed1ab_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=3_cp311
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=py311h06a4308_0
  - pyyaml=6.0.3=py311h591646f_0
  - pyzmq=27.1.0=py311h2315fbb_0
  - qhull=2020.2=h434a139_5
  - qtbase=6.7.3=h10a5587_3
  - qtdeclarative=6.7.3=h7934f7d_1
  - qtshadertools=6.7.3=h7934f7d_1
  - qtsvg=6.7.3=he4bddd1_1
  - qttools=6.7.3=h5a8de97_1
  - qtwebchannel=6.7.3=h7934f7d_1
  - qtwebengine=6.7.3=h5092597_1
  - qtwebsockets=6.7.3=h7934f7d_1
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=py311h06a4308_1
  - scikit-learn=1.8.0=py311hc3e1efb_0
  - scipy=1.16.0=py311h0cc6016_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - simsimd=6.5.0=py311h9ecbd09_0
  - six=1.17.0=pyhe01879c_1
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.6=py311h0372a8f_0
  - stringzilla=4.6.0=py311h49ec1c0_0
  - sympy=1.14.0=py311h06a4308_1
  - tbb=2021.8.0=hdb19cb5_0
  - tesseract=5.2.0=hb0d2e87_3
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_ha0e22de_103
  - torchtriton=2.1.0=py311
  - tornado=6.5.3=py311h49ec1c0_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h8577fbf_1
  - ultralytics=8.3.251=pyh865f8e1_0
  - unicodedata2=17.0.0=py311h49ec1c0_1
  - wayland=1.24.0=hdac8c69_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - x264=1!157.20191217=h7b6447c_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h387f397_9
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.2=h54a6638_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - filetype==1.2.0
      - fsspec==2025.12.0
      - idna==3.7
      - opencv-python-headless==4.10.0.84
      - pi-heif==1.1.1
      - pillow==12.1.0
      - pillow-avif-plugin==1.5.2
      - pyparsing==3.3.1
      - python-dotenv==1.2.1
      - requests-toolbelt==1.0.0
      - roboflow==1.2.11
      - torch==2.1.2+cu118
      - torchaudio==2.1.2+cu118
      - torchvision==0.16.2+cu118
      - urllib3==2.6.3
prefix: /home/rocinate/miniconda3/envs/ADLR
